### ISSUE TITLE
CVDR does not pass accelerator config to Orchestrator Service

### ISSUE THREAD

**Issue by gleichda** [google/cloud-android-orchestration#410]
When using `cvdr host create` CVDR does not pass the AcceleratorConfigs to the orchestrator service:
cvdr.toml
```toml
SystemDefaultService = "dockerIM"
[Services.dockerIM]
ServiceURL = "https://REDACTED"
Zone = "europe-west3-a"

Host={
        GCP={
                MachineType = "n1-standard-16",
                MinCPUPlatform = "Intel Haswell",
                BootDiskSizeGB = 100,
                AcceleratorConfigs=["count=1,type=nvidia-tesla-t4"]

        }
}
Authn={
        OIDCToken={
                TokenFile = "/tmp/cvdr_oidc.token"
        }
}
```

Logs from `cvdr host create`:
```
user@dev-instance:~$ cvdr host create -v
POST /v1/zones/europe-west3-a/hosts HTTP/1.1
Host: REDACTED
User-Agent: Go-http-client/1.1
Content-Length: 118
Authorization: Bearer REDACTED
Content-Type: application/json
Accept-Encoding: gzip

{"host_instance":{"gcp":{"machine_type":"n1-standard-16","min_cpu_platform":"Intel Haswell","boot_disk_size_gb":100}}}
HTTP/2.0 200 OK
Content-Length: 80
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Type: application/json
Date: Fri, 21 Feb 2025 09:14:36 GMT
Server: Google Frontend
Via: 1.1 google
X-Cloud-Trace-Context: e325d34647535a038fdd87a380295b24;o=1

{"name":"operation-1740129275905-62ea36b5a868d-450aff4e-f6430fa7","done":false}
```
